### ISSUE TITLE
OpSender is not recognized as it's wrapped type

### ISSUE THREAD

**Issue by willkroboth** [willkroboth/ConfigCommands#6]
## Plugins:
ConfigCommands v 1.0.1
[Multiverse](https://dev.bukkit.org/projects/multiverse-core)

## config.yml:
```
commands:
  hub:
    name: hub
    permission: navigation.hub
    shortDescription: Go to hub
    fullDescription: Sends the user back to the hub
    commands:
    - /mvtp hub
```

## Expected result:
When a player runs `/hub` the command `/mvtp hub` is run without the player needing a Multiverse teleporting permission, and the player is sent to the hub world.

## Actual result:
Nothing appears to happen from the player's side. Turning on debug mode and looking at the console, the call to `/mvtp hub` is returning the result: `"From the console, you must specify a player to teleport"`.

## Problem & Solution?
Multiverse seems to think that commands sent by OpSender are always from the console. To fix this, there might have to be a version of the OpSender that gets detected as a player by other plugins.
